name: Build and Deploy ROS2 Humble Docker

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io # Set GitHub Container Registry as default registry host for all jobs/steps.
  IMAGE_NAME: ${{ github.repository }} # Image name will be <owner>/<repo>

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Can read repository contents
      packages: write # Can push images to GitHub Container Registry.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Clones the repository code into the runner so later steps can access the Dockerfile and source.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Installs and configures Docker Buildx, enabling advanced build features (cache, multi-platform, etc.).

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3 # Log in to ghcr so subsequent steps can push images
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: |
            type=gha
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,mode=max
          cache-to: type=gha,mode=max
          provenance: false
          platforms: linux/amd64

      - name: Image digest
        run: echo "Image pushed with digest ${{ steps.build-push.outputs.digest }}"

